Basics of Tensorflow
from Book: Hands on Machine Learning

In [1]:
import tensorflow as tf
# Check if TensorFlow is using GPU support
print("Is GPU available:", tf.config.experimental.list_physical_devices('GPU'))


Is GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


Using constant method, this method is immutable which means the values dont change.

In [3]:
# create a tensor with tf.constant method
t=tf.constant([[1,2],[3,4]])
t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [4]:
t.shape
#to determine shape of tensor (row,column)

TensorShape([2, 2])

In [23]:
t.dtype
#to determine datatype

tf.int32

In [9]:
t[:1:]
#slicing of indices

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

Arithmetic operations

In [10]:
t+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [11]:
t-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [12]:
t*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [13]:
tf.square(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [14]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

Type Conversions

In [15]:
import numpy as np
a=np.array([2,4,5])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 4, 5])>

In [16]:
t.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>>

In [18]:
t1=tf.constant(40.)
tf.constant(2.0)+tf.cast(t1,tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

Variable method is not immutable i.e their values can change.

In [21]:
t2=tf.Variable([[3,4],[5,6]])
t2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

Variable method if you want to change value use .assign() method.

In [22]:
t2.assign(t2*2)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>